language: cpp
sudo: required
env: 
  global:
# Workaround for https://github.com/travis-ci/travis-ci/issues/4681
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true

matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true

  include:
    - os: linux
      dist: xenial
      env: 
      compiler: gcc
      addons:
          apt:
              packages: lcov
      before_install:
          - gcc --version
      before_install:
          # C++17
          - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          - sudo apt-get update -qq
      install: 
          # C++17
          - sudo apt-get install -qq g++-8 libboost-all-dev
          - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
      after_success:
          # Create lcov report
          # capture coverage info
          - lcov --directory . --capture --output-file coverage.info
          # filter out system and extra files.
          # To also not include test code in coverage add them with full path to the patterns: '*/tests/*'
          - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
          # output coverage data for debugging (optional)
          - lcov --list coverage.info
          # Uploading to CodeCov
          # '-f' specifies file(s) to use and disables manual coverage gathering and file search which has already been done above
          - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
    - os: osx
      osx_image: xcode10
      env:
      before_install:
          - brew install lcov
      after_success:
          # Creating report
          - cd ${TRAVIS_BUILD_DIR}
          - lcov --directory . --capture --output-file coverage.info # capture coverage info
          - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
          - lcov --list coverage.info #debug info
          # Uploading report to CodeCov
          - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

  allow_failures:
          - os: osx

script:
  - cmake -DCMAKE_BUILD_TYPE=Debug -DREAL_BENCH=OFF -G "Unix Makefiles" . && make -j`nproc` && ctest --verbose
